os:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
  - hg summary
  - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake
  - mkdir -p ign-cmake/build
  - cd ign-cmake/build
  - cmake ..
  - cmake --build . --target INSTALL
  - cd ../..
build_script:
  - md build
  - cd build
  - cmake .. -DEXTRA_CMAKE_CXX_FLAGS="-WX"
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS
  # Build the examples to make sure that find_package(ignition-math* REQUIRED) works
  - cd ../examples
  - md build 
  - cd build
  - cmake ..
  - cmake --build . --config %CONFIGURATION% 
  - cd ..
  
