# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get -y install cmake lcov
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - make install
          - make test
          # `make coverage` failing on pipelines, call lcov directly
          - ls -l
          - lcov -q --no-checksum --directory . --capture --output-file coverage.info.full
          - ls -l
          - cat coverage.info.full | grep test
          - lcov -q --remove coverage.info.full '*test*' '/usr/*' '*_TEST*' --output-file coverage.info
          - ls -l
          - cat coverage.info | grep test
          - rm coverage.info.full
          - bash <(curl -s https://codecov.io/bash)

