image: ubuntu:zesty

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install cmake build-essential lcov curl mercurial cppcheck ruby-dev swig
          - gcc -v
          - g++ -v
          # Static checking before building - fail fast
          - sh tools/code_check.sh
          # Ignition cmake
          - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake ..
          - make install
          - cd ../..
          # Ignition math
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make install
          # Examples
          - cd ..
          - cd examples
          - mkdir build
          - cd build
          - cmake ..
          - make
          - ./graph_example
