image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install cmake build-essential lcov curl mercurial
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b CMakeRefactor
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake ..
          - make install
          - cd ../..
          # Ignition math
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
