image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install cmake build-essential lcov curl mercurial cppcheck ruby-dev swig
          - gcc -v
          - g++ -v
          # Static checking before building - fail fast
          - sh tools/code_check.sh
          # Ignition cmake
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          #- apt-get update
          #- apt-get -y install
          #  libignition-cmake-dev
          # build ign-cmake from source
          - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake -b no_branch_coverage
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. -DBUILD_TESTING=OFF
          - make install
          - cd ../..
          # Ignition math
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make install
          # Examples
          - cd ..
          - cd examples
          - mkdir build
          - cd build
          - cmake ..
          - make
          - ./graph_example
