codecov:
  branch: default

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
  lcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
